version: "3.4"

volumes:
  simplify-db-data:
    driver: local

services:
  php:
    container_name: simplify-php
    tty: true
    build:
      context: ./
    volumes:
      - ./:/var/www/
    ports:
      - "9599:9501"
#    entrypoint: bash -c "/usr/bin/supervisord -c /etc/supervisord.conf"
    environment:
      - PHP_IDE_CONFIG=serverName=${APP_NAME}
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: simplify-db
    volumes:
      - simplify-db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simplify
      MYSQL_TCP_PORT: 3316
    ports:
      - "3399:3316"
